Repository Sjoerd1993/Graphs, pull requests merged in 2023-02, with the labels that each got.

#70 WIP: Fix selection on log scale
  src/item_operations.py
Labels: bug

#65 WIP: Perform item operations only on highlighted area
  src/add_equation.py
  src/graphs.py
  src/item_operations.py
  src/main.py
  src/plotting_tools.py
  src/transform_data.py
Labels: enhancement, needs work

#74 redesign ui elements
  data/ui/window.ui
  src/graphs.py
  src/item_operations.py
  src/main.py
  src/meson.build
  src/plotting_tools.py
  src/toolbar.py
  src/utilities.py
  src/window.py
Labels: enhancement

#79 Add combine data feature
  data/ui/preferences.ui
  data/ui/window.ui
  src/graphs.py
  src/item_operations.py
  src/main.py
  src/plot_settings.py
  src/plotting_tools.py
  src/utilities.py
  src/window.py
Labels: enhancement

#88 add custom stylesheets
  data/config.json
  data/meson.build
  data/styles/adwaita-dark.mplstyle
  data/styles/adwaita.mplstyle
  src/plotting_tools.py
Labels: enhancement

#100 Add "Save as project" functionality
  data/ui/window.ui
  src/colorpicker.py
  src/data.py
  src/graphs.py
  src/item_operations.py
  src/main.py
  src/plot_settings.py
  src/preferences.py
  src/project.py
  src/samplerow.py
  src/utilities.py
Labels: enhancement

#115 Add unique icons
  data/icons/center-symbolic.svg
  data/icons/derivative2-symbolic.svg
  data/icons/fast-fourier-transform-symbolic.svg
  data/icons/horizontal-arrows-symbolic.svg
  data/icons/integral-symbolic.svg
  data/icons/inverse-fast-fourier-transform-symbolic.svg
  data/icons/normalize-symbolic.svg
  data/icons/shift-symbolic.svg
  data/icons/smoothen-symbolic.svg
  data/icons/transform-symbolic.svg
  data/icons/vertical-arrows-symbolic.svg
  data/se.sjoerd.Graphs.gresource.xml
  data/ui/window.ui
Labels: enhancement

#113 Switch to cairo backend for figurecanvas
  src/plotting_tools.py
Labels: bug

#120 implement own rubberband zoom
  src/graphs.py
  src/plotting_tools.py
  src/utilities.py
Labels: enhancement

#131 refactoring
  src/add_data_advanced.py
  src/add_equation.py
  src/canvas.py
  src/data.py
  src/file_io.py
  src/graphs.py
  src/item_operations.py
  src/main.py
  src/meson.build
  src/misc.py
  src/plotting_tools.py
  src/project.py
  src/rename_label.py
  src/transform_data.py
  src/ui.py
  src/utilities.py
Labels: enhancement
